# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3253839cb5ba5734a444f3a9d82e2cc57917fab60568fd1a0bec3e56f0b18d3df95f2901e68e628ffe20d0932eafde7f549039261e17a35757990a65ea232c6

test:
  secret_key_base: f5826fba1aca4b90d97380ead7b9b686af52a0202402d9d641236b4580b42c74a642ba071195ccc7990510d627de4e94bc83e1271337ad52f8fc06818167cac3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
